
DO $$
BEGIN

CREATE SEQUENCE IF NOT EXISTS "person"."address_addressid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "person"."addresstype_addresstypeid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "person"."businessentity_businessentityid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "person"."contacttype_contacttypeid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "person"."emailaddress_emailaddressid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "person"."phonenumbertype_phonenumbertypeid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "person"."stateprovince_stateprovinceid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

END
$$;