
DO $$
BEGIN

CREATE SEQUENCE IF NOT EXISTS "sales"."creditcard_creditcardid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "sales"."currencyrate_currencyrateid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "sales"."customer_customerid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "sales"."salesorderdetail_salesorderdetailid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "sales"."salesorderheader_salesorderid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "sales"."salesreason_salesreasonid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "sales"."salestaxrate_salestaxrateid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "sales"."shoppingcartitem_shoppingcartitemid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "sales"."specialoffer_specialofferid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "sales"."salesterritory_territoryid_seq"
  AS INT INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  START WITH 1
  CACHE 1
  NO CYCLE;

END
$$;