name: json-yaml-validate
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # SQL Server
          - name: SqlServer-AdventureWorks
            schema: SqlServer/AdventureWorks/.json-schemas/tables.sqlserver.schema
            base_dir: SqlServer/AdventureWorks/Templates/AdventureWorks/Tables
          - name: SqlServer-Northwind
            schema: SqlServer/Northwind/.json-schemas/tables.sqlserver.schema
            base_dir: SqlServer/Northwind/Templates/Northwind/Tables
          - name: SqlServer-ValidProduct
            schema: SqlServer/ValidProduct/.json-schemas/tables.sqlserver.schema
            files: |
              SqlServer/ValidProduct/Templates/Main/Tables/**/*.json
              SqlServer/ValidProduct/Templates/Secondary/Tables/**/*.json
          # PostgreSQL
          - name: PostgreSQL-AdventureWorks
            schema: PostgreSQL/AdventureWorks/.json-schemas/tables.postgresql.schema
            base_dir: PostgreSQL/AdventureWorks/Templates/AdventureWorks/Tables
          - name: PostgreSQL-DVDRental
            schema: PostgreSQL/DVDRental/.json-schemas/tables.postgresql.schema
            base_dir: PostgreSQL/DVDRental/Templates/DVDRental/Tables
          - name: PostgreSQL-Northwind
            schema: PostgreSQL/Northwind/.json-schemas/tables.postgresql.schema
            base_dir: PostgreSQL/Northwind/Templates/Northwind/Tables
          - name: PostgreSQL-ValidProduct
            schema: PostgreSQL/ValidProduct/.json-schemas/tables.postgresql.schema
            files: |
              PostgreSQL/ValidProduct/Templates/Main/Tables/**/*.json
              PostgreSQL/ValidProduct/Templates/Secondary/Tables/**/*.json
          # MySQL
          - name: MySQL-Sakila
            schema: MySQL/Sakila/.json-schemas/tables.mysql.schema
            base_dir: MySQL/Sakila/Templates/Sakila/Tables
          - name: MySQL-ValidProduct
            schema: MySQL/ValidProduct/.json-schemas/tables.mysql.schema
            files: |
              MySQL/ValidProduct/Templates/Main/Tables/**/*.json
    steps:
      - uses: actions/checkout@v4

      - name: Validate ${{ matrix.name }}
        uses: GrantBirki/json-yaml-validate@v2.6.0
        with:
          comment: "true"
          use_gitignore: "false"
          ajv_strict_mode: "false"
          json_schema: ${{ matrix.schema }}
          base_dir: ${{ matrix.base_dir || '' }}
          files: ${{ matrix.files || '' }}
